#建议使用github源，pod install前请检查终端代理网络是否通畅(可能需要通过代码给终端设置代理，否则终端不会走代理服务，具体请检查您的代理服务流量变化)，如遇失败可尝试使用pod install --repo-update命令
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '13.0'

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
         end
    end
  end
end

target 'iOSDemo' do
  use_frameworks!
  
  # 国内Taku
  pod 'ATMentaCNAdapter', :path => './../ATMentaCNAdapter.podspec'
  
  # 示例
  pod 'AnyThinkiOS'
  pod 'AnyThinkMediationMSAdapter','2.7.13.0.0'
  pod 'AnyThinkDebugUISDK'
  
  # Demo UI依赖的第三库
  pod 'Masonry'
  pod 'SDWebImage'
  pod 'MJRefresh'
  pod 'SVProgressHUD'
   
end
